### ISSUE TITLE
Permission Issue When Deploying Via Unraid

### ISSUE THREAD

**Issue by kylehandy123** [HeyPuter/puter#395] opened 2024-05-13 09:39 UTC
**Issue Description**
I am deploying Puter via a template I created in unraid, following the docker compose file provided. Despite setting PUID & PGID values in the template, which is equivalent to:
    environment:
      # TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
The logs state the following: [BOOT/ERROR] Error: Cannot write to path: /var/puter
**Steps to Reproduce**
Attempt to deploy a Docker container of this software following the Docker Compose file in Unraid.
**Expected & Actual Behavior**
The container to run and be usable.
**Addition Information or Screenshots (if applicable)**
NOTE: running "sudo chown -R 1000:1000 puter" in the Unraid terminal does fix this issue.
**Deployment**
- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [x] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by AtkinsSJ** [comment] 2024-05-13 15:36
There are definitely [some issues](https://github.com/HeyPuter/puter/issues/375) with the Docker configuration, so I'm not surprised that you're having problems modifying it for a different platform. Personally I'm unfamiliar with Docker so it's hard to figure out what needs changing.

**Comment by KernelDeimos** [comment] 2024-11-07 03:01
I'm considering this a duplicate of #645 , so I'll close this one and discussion can happen there

**Closed by KernelDeimos** 2024-11-07 03:01 UTC
Labels: community
