### ISSUE TITLE
Puter Docker - No login via browser (intermittent wallpaper display)

### ISSUE THREAD

**Issue by ianweatherburn** [HeyPuter/puter#350] opened 2024-04-26 09:04 UTC
**Issue Description**
puter is started via docker and is active at http://192.168.0.152:4100
![CleanShot 2024-04-26 at 11 01 30](https://github.com/HeyPuter/puter/assets/19514284/5752b588-c19b-4c7a-a560-cd6dec3374c1)
however fancy wallpaper intermittently appears in browser (mostly, not at all unless I clear cache - otherwise plain dark-blue background), 
and more importantly, NO login appears at all so I cannot enter the default credentials provided to continue configuration.
Container shows as healthy, via the health-check so it is responding to the wget's

**Steps to Reproduce**
mount docker container via docker-compose.yml
[docker-compose.yml]
puter:
    image: ghcr.io/heyputer/puter:latest
    container_name: puter
    restart: unless-stopped
    pull_policy: always
    environment:
      - 'PUID=${PUID}'
      - 'PGID={PGID}'
      - 'TZ=${TZ}'
      - 'CONFIG_PATH=/etc/puter'
    ports:
      - '${PUTER}:4100' 
    volumes:
      - '${DATA}/puter/config:/etc/puter'
      - '${DATA}/puter/data:/var/puter'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

.env variables
PUTER=4100
PGID=1000
PUID=1000
TZ=Africa/Johannesburg
DATA=/home/iwadmin/docker/appdata

**Expected & Actual Behavior**
Login screen where default user credentials provided by the container can be captured and configuration/setup can continue/complete.

**Addition Information or Screenshots (if applicable)**
[config.json]
{
    "config_name": "generated default config",
    "env": "dev",
    "nginx_mode": true,
    "server_id": "ISENGARD",
    "http_port": "4100",
    "domain": "192.168.0.152",
    "protocol": "http",
    "contact_email": "hey@example.com",
    "services": {
        "database": {
            "engine": "sqlite",
            "path": "puter-database.sqlite"
        },
        "thumbnails": {
            "engine": "purejs"
        },
        "file-cache": {
            "disk_limit": 16384,
            "disk_max_size": 16384,
            "precache_size": 16384,
            "path": "./file-cache"
        }
    },
    "cookie_name": "b302d23a-2cc1-48e8-b3c7-de3638c26e08",
    "jwt_secret": "ce90b02f-38b5-430e-84e8-444430c7e08f",
    "url_signature_secret": "6363a124-c639-48aa-886a-1a90063fadc9",
    "": null
}

**Deployment**
- [ ] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [X] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom
Unable to access Settings as cannot login
ghcr.io/heyputer/puter:latest

** DEV CONSOLE Docker Output**
puter> 
[INFO::morgan] method="GET" url="/test?" status=200 responseTime=5.226 trace_request="846499a1-5623-4bf4-831f-2b8c7edcd2e1" (8230.099s) GET /test? 200 5.226
[ Dev Console ]
 *** WARNING ** WARNING ** WARNING ***
 [alarm] bold-wallet-1101 (INVALID SYSTEM STATE...): failed to initialize services (1)
 *** WARNING ** WARNING ** WARNING ***
 *** SYSTEM IS IN AN INVALID STATE *** 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                   ┃
┃  Puter is now live at: ]8;;http://192.168.0.152:4100\http://192.168.0.152:4100]8;;\  ┃
┃  Type web:dismiss to dismiss this message         ┃
┃                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Your default user has been created!           ┃
┃  username: default_user                        ┃
┃  password: 33c7b6a7                            ┃
┃  (change the password to remove this message)  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

**Comment by ianweatherburn** [comment] 2024-04-29 09:18
![CleanShot 2024-04-29 at 11 17 25](https://github.com/HeyPuter/puter/assets/19514284/874759ae-1cfd-42b2-9e17-cc2170b9056d)
Further console info

**Comment by AtkinsSJ** [comment] 2024-04-29 10:20
This looks like the same as #230, you could try this solution from there:


> So far we've added a config option to remove the requirement of a `api.` subdomain:
> ```json
>     "experimental_no_subdomain": true,
> ```

_Originally posted by @KernelDeimos in https://github.com/HeyPuter/puter/issues/230#issuecomment-2065864940_

**Comment by ianweatherburn** [comment] 2024-04-29 10:32
> This looks like the same as #230, you could try this solution from there:
> 
> > So far we've added a config option to remove the requirement of a `api.` subdomain:
> > ```json
> >     "experimental_no_subdomain": true,
> > ```
> 
> _Originally posted by @KernelDeimos in [#230 (comment)](https://github.com/HeyPuter/puter/issues/230#issuecomment-2065864940)_

Thank you. This has fixed the issue.

**Comment by AtkinsSJ** [comment] 2024-05-01 09:31
> Thank you. This has fixed the login issue. However, no App Centre, Dev Center, no Browser, Terminal doesn't work.

App Centre, Dev Center, and Browser being missing is expected, we don't include those now, but we will do later.

Can you explain what issues you're having with the Terminal?

**Comment by ianweatherburn** [comment] 2024-05-02 07:27
Thanks for the clarification. Terminal fails to start. Window opens, cursor, no prompt. No error message in docker logs.
![CleanShot 2024-05-02 at 09 24 43](https://github.com/HeyPuter/puter/assets/19514284/5b11b229-a616-4b4e-b1bd-18351e118757)

**Comment by AtkinsSJ** [comment] 2024-05-02 10:31
OK. First, after opening Terminal, can you have a look at the Task Manager in Puter? It's in this menu and should have an entry for "phoenix" underneath the "terminal" one, like so:
![image](https://github.com/HeyPuter/puter/assets/222642/3c106816-721d-4991-be57-b481207891a3)

Second, if you can look at the browser console again, there should be some kind of clue there.

And finally, what version of Puter is it running? It'll be on the "About" tab of the Settings app. We did recently have issues with the terminal and I don't know how Docker updates things, but it might be running an older version somehow.

**Comment by ianweatherburn** [comment] 2024-05-02 13:39
1. Task Manager is in line with your screenshot.
![CleanShot 2024-05-02 at 15 31 18](https://github.com/HeyPuter/puter/assets/19514284/049e0b99-c328-4fc2-85dd-1f33bec8cbe1)

2. Browser Javascript Console after launching Terminal
Arc Browser v1.40.1
![CleanShot 2024-05-02 at 15 34 52](https://github.com/HeyPuter/puter/assets/19514284/7bc46e1a-747d-486f-989a-acdc82848422)
Safari Browser v17.14.1
![CleanShot 2024-05-02 at 15 38 04](https://github.com/HeyPuter/puter/assets/19514284/5c74ce84-5f19-4e64-8e55-8e8fdde48e39)

3. Puter Docker Version :latest
Version: 2.1.0 • Server: ISENGARD • Deployed: 02/05/2024, 15:31:56

**Comment by AtkinsSJ** [comment] 2024-05-06 08:37
Thanks. I'm a bit confused. The errors that `contextlink` and `main_shell` are not defined mean it's probably an issue with installing nested dependencies - but that should have been fixed before 2.1.0.

I'm going to spend some time today setting up Docker to see if I can reproduce this.

**Comment by AtkinsSJ** [comment] 2024-06-28 13:56
This should be fixed by https://github.com/HeyPuter/puter/commit/fa7bec38547bb7fff29cd60e320f98d146754c13

**Closed by AtkinsSJ** 2024-06-28 13:56 UTC
