### ISSUE TITLE
@heyputer/backend import error

### ISSUE THREAD

**Issue by says112** [HeyPuter/puter#236] opened 2024-04-05 11:14 UTC
![Снимок экрана (762)](https://github.com/HeyPuter/puter/assets/22127398/88c1ab06-ae13-48da-8f92-1fe8ea4a112d)
He's not going to.

**Comment by Kreijstal** [comment] 2024-04-05 16:45
Nooooo they lied to me, I'll never recover

**Comment by KernelDeimos** [comment] 2024-04-05 17:22
@says112 @Kreijstal - did you run `npm install`?

**Comment by KernelDeimos** [comment] 2024-04-05 18:24
I tested a fresh clone without running `npm install` and successfully reproduced the error, so I'm closing this issue. I'm also going to put the original title back because it's funny.

**Closed by KernelDeimos** 2024-04-05 18:24 UTC
